### ISSUE TITLE
Use sphinx and breathe from the system to build documentation

### ISSUE THREAD

**Issue by daveisfera** [fmtlib/fmt#443]
I'm trying to build the documentation as part of packaging for Fedora, but sphinx and breathe are pulled from github instead of using the system versions. Could this be fixed so the sphinx and breathe from the system are used all the time or at least when available?

For reference, the failed build can be found [here](https://koji.fedoraproject.org/koji/taskinfo?taskID=17099257).

**Comment by vitaut** [comment]
Unfortunately using system Sphinx and Breathe most definitely won't work unless very specific versions are installed. As for the error, it seems to be caused by inability to fetch dependencies via the git protocol. If this is the case https://github.com/fmtlib/fmt/commit/02553d13a0242809fbe54f1d123f0e44eec70f2e should fix it.

**Comment by daveisfera** [comment]
It still fails with that change ( https://koji.fedoraproject.org/koji/taskinfo?taskID=17110916 ).

Fedora Rawhide (26) have sphinx 1.4.9 and breathe 4.4.0. Are those not new enough to build the documentation?

**Comment by AdamWill** [comment]
"As for the error, it seems to be caused by inability to fetch dependencies via the git protocol."

No, it's failing because Fedora package builds are run without any network access, by policy.

**Comment by vitaut** [comment]
Thanks for clarification, @AdamWill. This makes a lot of sense.

@daveisfera, I recommend using one of the packages with generated documentation such as [fmt-3.0.1](https://github.com/fmtlib/fmt/releases/download/3.0.1/fmt-3.0.1.zip) then. C++ support in Sphinx has been under heavy development and I don't know if the documentation will be generated properly with sphinx 1.4.9 and breathe 4.4.0 (and I don't have time to investigate it right now).

**Comment by daveisfera** [comment]
I [patched out](http://pkgs.fedoraproject.org/cgit/rpms/fmt.git/commit/?id=d4aee5a0efd23707c5ed7c448cdf13042c1bb2f1) the virtualenv stuff so the system versions of sphinx and breathe would be used. It built and it looked correct to me, but when I build without network access the call to doxygen [still fails](https://koji.fedoraproject.org/koji/taskinfo?taskID=17112625). Any ideas?

**Comment by vitaut** [comment]
The log shows that there was a segfault in doxygen:

```
subprocess.CalledProcessError: Command '['doxygen', '-']' returned non-zero exit status -11
```
I recommend [submitting a bug report](https://www.stack.nl/~dimitri/doxygen/manual/trouble.html#bug_reports).

**Comment by daveisfera** [comment]
I was trying to make a minimal reproducer to submit a bug to doxygen but it's worked fine without network access in all of my tests. Also, several other Fedora packages use doxygen without issue (here are [a](http://pkgs.fedoraproject.org/cgit/rpms/gumbo-parser.git/tree/gumbo-parser.spec#n62) [few](http://pkgs.fedoraproject.org/cgit/rpms/libfreenect.git/tree/libfreenect.spec#n132) [examples](http://pkgs.fedoraproject.org/cgit/rpms/libtevent.git/tree/libtevent.spec)), so it appears that this is something specific to how building the documentation for `fmt` is using doxygen.

I noticed that `fmt` runs it with `-` to read from `stdout` and then pipes in parameters. I'm not all that familiar with doxygen, but could doing that instead of using a config file be causing the problem?

**Comment by vitaut** [comment]
> I'm not all that familiar with doxygen, but could doing that instead of using a config file be causing the problem?

Could be. I also saw multiple bugs related to XML generation in doxygen in the past (but none of those was causing a crash).

Can you reproduce the crash when building full fmt docs? If yes, then I don't think you need to come  up with a minimal reproducer. The library is small enough for the doxygen devs to be able to reproduce the issue in seconds.

**Comment by daveisfera** [comment]
The issue with doxygen has been resolved, so for Fedora packaging the docs are built from source using the system executables. Thanks for the help and making this an option or at least making it so it's not too hard for me to patch out the download would be great.
https://koji.fedoraproject.org/koji/buildinfo?buildID=829945

**Comment by vitaut** [comment]
Thanks for the update, @daveisfera, and, as always, for your work on packaging the library for Fedora.

> Thanks for the help and making this an option or at least making it so it's not too hard for me to patch out the download would be great.

OK, I'll reopen this issue and will add an option. Can't promise that it will happen any time soon though, because I'm focused on the standards proposal.
